name: update
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - name: Update README
        uses: actions/github-script@v6
        with:
          script: |
            const script = require('./src/update.js');
            await script({ core, apiKey: '${{ secrets.GHOST_API_KEY }}', ghostUrl: '${{ secrets.GHOST_URL }}' });
      - name: deploy changes
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -m ":rocket:: updated blog content"
          git push -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
